import SEO from '../components/SEO';
import { NavLink } from 'react-router-dom';
import { services } from '../data/services';
import { technologies } from '../data/technologies';

export default function Home() {
  return <><SEO title="NexGen Engineers | Software, Cloud & AI Solutions" description="NexGen Engineers builds modern software, cloud, AI and automation solutions for growing businesses." />
    <section className="hero-section py-5"><div className="container py-5"><div className="row align-items-center g-5"><div className="col-lg-7"><span className="eyebrow">Software • Cloud • AI • Automation</span><h1 className="display-3 fw-bold text-white mt-3">Build. Scale. <span className="gradient-text">Transform.</span></h1><p className="lead text-white-50 mt-4 col-xl-10">We design and develop modern applications, enterprise software and AI-powered solutions that turn business ideas into reliable digital products.</p><div className="d-flex flex-column flex-sm-row gap-3 mt-4"><NavLink className="btn btn-primary btn-lg px-4" to="/contact">Start a Project <i className="bi bi-arrow-up-right ms-2"></i></NavLink><NavLink className="btn btn-outline-light btn-lg px-4" to="/portfolio">Explore Our Work</NavLink></div></div><div className="col-lg-5"><div className="hero-card"><span className="text-white-50 small">NexGen Delivery</span>{['design solution','build platform','integrate ai','deploy to cloud'].map(x=><div className="terminal-line" key={x}><span>$</span>{x}</div>)}<div className="terminal-result mt-4">✓ Product ready for growth</div></div></div></div></div></section>
    <section className="section-space"><div className="container"><span className="eyebrow">What we do</span><h2 className="display-6 fw-bold mt-2 mb-5">Technology that solves real business problems.</h2><div className="row g-4">{services.map(s=><div className="col-md-6 col-xl-4" key={s.title}><div className="service-card h-100"><div className="icon-box"><i className={'bi '+s.icon}></i></div><h4 className="mt-4">{s.title}</h4><p className="text-secondary mb-0">{s.text}</p></div></div>)}</div></div></section>
    <section className="section-space bg-light-subtle"><div className="container"><div className="row g-5 align-items-center"><div className="col-lg-6"><span className="eyebrow">Why NexGen</span><h2 className="display-6 fw-bold mt-2">A delivery mindset, not just a coding mindset.</h2><p className="text-secondary mt-3">We combine product thinking, engineering discipline and practical cloud/AI capabilities to deliver solutions that are easier to operate and evolve.</p>{['Clear scope and milestones','Modular, maintainable code','Security-first API design','Deployment and handover support'].map(x=><div className="feature-row" key={x}><i className="bi bi-check-circle-fill me-3"></i>{x}</div>)}</div><div className="col-lg-6"><div className="process-panel">{['Discover','Design','Develop','Deploy','Improve'].map((x,i)=><div className="process-step" key={x}><span>0{i+1}</span><strong>{x}</strong><small>{['Understand goals and requirements','Shape UX and architecture','Build with quality gates','Release with confidence','Measure and enhance'][i]}</small></div>)}</div></div></div></div></section>
    <section className="section-space dark-section"><div className="container"><span className="eyebrow">Technology stack</span><h2 className="display-6 fw-bold text-white mt-2">Modern technologies, selected for the job.</h2><div className="d-flex flex-wrap gap-2 mt-4">{technologies.map(t=><span className="tech-chip" key={t}>{t}</span>)}</div></div></section>
    <section className="section-space"><div className="container"><div className="cta-panel text-center p-5"><span className="eyebrow">Have an idea?</span><h2 className="display-6 fw-bold mt-2">Let’s turn it into a product.</h2><p className="text-secondary">Tell us what you want to build, your target users and your timeline.</p><NavLink className="btn btn-primary btn-lg px-4 mt-3" to="/contact">Talk to NexGen</NavLink></div></div></section>
  </>;
}